### ISSUE TITLE
apkpatch-1.0.3.zip是什么东西啊，

### ISSUE THREAD

**Issue by fanluo** [fanhua1994/BaseAndroid#5]
apkpatch-1.0.3.zip大小有10M，太大了吧

**Comment by fanluo** [comment]
建议外面给下载地址，后面单独建个git项目提供这个下载

**Comment by fanhua1994** [comment]
这个是不会影响你引用XBaseAndroid。不会打包到lib包。这个是之前接入的热更新组件。下个版本清理。
